#:kivy 2.2.1

# <-fullImage>
#     canvas:
#         Color:
#             rgb: (1, 1, 1)
#         Rectangle:
#             texture: self.texture
#             size: self.width + 20, self.height + 20
#             pos: self.x - 10, self.y - 10


<-fullImage>
    canvas:
        Color:
            rgba: [1, 0, 0, 1]
    
        Rectangle:
            size: self.size[0], self.size[1]
            pos: self.pos
    
    
